version: '3.8'

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    image: custom-elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    build:
      context: ./logstash
    image: custom-logstash
    container_name: logstash
    volumes:
      - ./input_logs:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./kibana
    image: custom-kibana
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  elk:
    driver: bridge
