version: '3'

services:
  flaskapp:
    image: flaskapp
    build:
      context: ./Flask
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    networks:
      - monitoring

  prometheus:
    image: prometheus
    build:
      context: ./Prometheus
      dockerfile: Dockerfile.prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana
    build:
      context: ./Grafana
      dockerfile: Dockerfile.grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
